# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actors.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x63tors.proto\x12\x06\x61\x63tors\"5\n\x0fRegisterRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\x0c\x12\x10\n\x08owner_id\x18\x02 \x01(\x0c\"3\n\rUpdateRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\x0c\x12\x10\n\x08owner_id\x18\x02 \x01(\x0c\"\x07\n\x05\x45mpty2|\n\x0c\x41\x63torService\x12\x37\n\rRegisterActor\x12\x17.actors.RegisterRequest\x1a\r.actors.Empty\x12\x33\n\x0bUpdateActor\x12\x15.actors.UpdateRequest\x1a\r.actors.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actors_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREQUEST._serialized_start=24
  _REGISTERREQUEST._serialized_end=77
  _UPDATEREQUEST._serialized_start=79
  _UPDATEREQUEST._serialized_end=130
  _EMPTY._serialized_start=132
  _EMPTY._serialized_end=139
  _ACTORSERVICE._serialized_start=141
  _ACTORSERVICE._serialized_end=265
# @@protoc_insertion_point(module_scope)
