# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.proto import driverworker_pb2 as driverworker__pb2


class DriverWorkerServiceStub(object):
    """Driver to Worker
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/hive.DriverWorkerService/Execute',
                request_serializer=driverworker__pb2.TaskRequest.SerializeToString,
                response_deserializer=driverworker__pb2.TaskReply.FromString,
                )
        self.GetLoad = channel.unary_unary(
                '/hive.DriverWorkerService/GetLoad',
                request_serializer=driverworker__pb2.LoadRequest.SerializeToString,
                response_deserializer=driverworker__pb2.LoadReply.FromString,
                )


class DriverWorkerServiceServicer(object):
    """Driver to Worker
    """

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=driverworker__pb2.TaskRequest.FromString,
                    response_serializer=driverworker__pb2.TaskReply.SerializeToString,
            ),
            'GetLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoad,
                    request_deserializer=driverworker__pb2.LoadRequest.FromString,
                    response_serializer=driverworker__pb2.LoadReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hive.DriverWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DriverWorkerService(object):
    """Driver to Worker
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hive.DriverWorkerService/Execute',
            driverworker__pb2.TaskRequest.SerializeToString,
            driverworker__pb2.TaskReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hive.DriverWorkerService/GetLoad',
            driverworker__pb2.LoadRequest.SerializeToString,
            driverworker__pb2.LoadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
