# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\x12\x04hive\"&\n\x10ObjectLocRequest\x12\x12\n\nobject_ids\x18\x01 \x01(\x0c\"$\n\x0eObjectLocReply\x12\x12\n\nworker_ids\x18\x01 \x01(\x0c\x32M\n\rDriverService\x12<\n\x0cGetObjectLoc\x12\x16.hive.ObjectLocRequest\x1a\x14.hive.ObjectLocReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECTLOCREQUEST._serialized_start=22
  _OBJECTLOCREQUEST._serialized_end=60
  _OBJECTLOCREPLY._serialized_start=62
  _OBJECTLOCREPLY._serialized_end=98
  _DRIVERSERVICE._serialized_start=100
  _DRIVERSERVICE._serialized_end=177
# @@protoc_insertion_point(module_scope)
