# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"A\n\x0e\x45xecuteRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x0c\x12\x10\n\x08\x66unction\x18\x02 \x01(\x0c\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\x0c\" \n\rCancelRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x0c\"/\n\x0c\x45xecuteReply\x12\x0f\n\x07task_id\x18\x01 \x01(\x0c\x12\x0e\n\x06result\x18\x02 \x01(\x0c\"\x1e\n\x0b\x43\x61ncelReply\x12\x0f\n\x07task_id\x18\x01 \x01(\x0c\x32\x80\x01\n\x0bTaskService\x12\x39\n\x0b\x45xecuteTask\x12\x15.tasks.ExecuteRequest\x1a\x13.tasks.ExecuteReply\x12\x36\n\nCancelTask\x12\x14.tasks.CancelRequest\x1a\x12.tasks.CancelReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXECUTEREQUEST._serialized_start=22
  _EXECUTEREQUEST._serialized_end=87
  _CANCELREQUEST._serialized_start=89
  _CANCELREQUEST._serialized_end=121
  _EXECUTEREPLY._serialized_start=123
  _EXECUTEREPLY._serialized_end=170
  _CANCELREPLY._serialized_start=172
  _CANCELREPLY._serialized_end=202
  _TASKSERVICE._serialized_start=205
  _TASKSERVICE._serialized_end=333
# @@protoc_insertion_point(module_scope)
