# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.proto import workerworker_pb2 as workerworker__pb2


class WorkerWorkerServiceStub(object):
    """Worker to Worker
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObject = channel.unary_unary(
                '/hive.WorkerWorkerService/GetObject',
                request_serializer=workerworker__pb2.ObjectRequest.SerializeToString,
                response_deserializer=workerworker__pb2.ObjectReply.FromString,
                )


class WorkerWorkerServiceServicer(object):
    """Worker to Worker
    """

    def GetObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=workerworker__pb2.ObjectRequest.FromString,
                    response_serializer=workerworker__pb2.ObjectReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hive.WorkerWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkerWorkerService(object):
    """Worker to Worker
    """

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hive.WorkerWorkerService/GetObject',
            workerworker__pb2.ObjectRequest.SerializeToString,
            workerworker__pb2.ObjectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
