# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workerworker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12workerworker.proto\x12\x04hive\"#\n\rObjectRequest\x12\x12\n\nobject_ids\x18\x01 \x01(\x0c\"\x1e\n\x0bObjectReply\x12\x0f\n\x07objects\x18\x01 \x01(\x0c\x32J\n\x13WorkerWorkerService\x12\x33\n\tGetObject\x12\x13.hive.ObjectRequest\x1a\x11.hive.ObjectReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workerworker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECTREQUEST._serialized_start=28
  _OBJECTREQUEST._serialized_end=63
  _OBJECTREPLY._serialized_start=65
  _OBJECTREPLY._serialized_end=95
  _WORKERWORKERSERVICE._serialized_start=97
  _WORKERWORKERSERVICE._serialized_end=171
# @@protoc_insertion_point(module_scope)
