# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x04hive\">\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x0c\x12\x10\n\x08\x66unction\x18\x02 \x01(\x0c\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\x0c\",\n\tTaskReply\x12\x0f\n\x07task_id\x18\x01 \x01(\x0c\x12\x0e\n\x06result\x18\x02 \x01(\x0c\"#\n\rObjectRequest\x12\x12\n\nobject_ids\x18\x01 \x01(\x0c\"\x1e\n\x0bObjectReply\x12\x0f\n\x07objects\x18\x01 \x01(\x0c\"\r\n\x0bLoadRequest\"2\n\tLoadReply\x12\x10\n\x08\x63pu_load\x18\x01 \x01(\x0c\x12\x13\n\x0bmemory_util\x18\x02 \x01(\x0c\x32\xa2\x01\n\rWorkerService\x12-\n\x07\x45xecute\x12\x11.hive.TaskRequest\x1a\x0f.hive.TaskReply\x12\x33\n\tGetObject\x12\x13.hive.ObjectRequest\x1a\x11.hive.ObjectReply\x12-\n\x07GetLoad\x12\x11.hive.LoadRequest\x1a\x0f.hive.LoadReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASKREQUEST._serialized_start=22
  _TASKREQUEST._serialized_end=84
  _TASKREPLY._serialized_start=86
  _TASKREPLY._serialized_end=130
  _OBJECTREQUEST._serialized_start=132
  _OBJECTREQUEST._serialized_end=167
  _OBJECTREPLY._serialized_start=169
  _OBJECTREPLY._serialized_end=199
  _LOADREQUEST._serialized_start=201
  _LOADREQUEST._serialized_end=214
  _LOADREPLY._serialized_start=216
  _LOADREPLY._serialized_end=266
  _WORKERSERVICE._serialized_start=269
  _WORKERSERVICE._serialized_end=431
# @@protoc_insertion_point(module_scope)
